<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../STAVCMS.LocalServer.Core/STAVCMS.LocalServer.Core.csproj" />
    <ProjectReference Include="../STAVCMS.LocalServer.Server/STAVCMS.LocalServer.Server.csproj" />
  </ItemGroup>
</Project>
